# Site settings
name: Daniel Le
email: sonhailenguyen@gmail.com
keywords: "Software Developer, Python, iOS"
skills: "Software Developer"
baseurl: daniel-le.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/daniel-le18/
  - title: github
    url: https://github.com/daniel-le18
  - title: paper-plane
    url: "mailto:sonhailenguyen@gmail.com"

# Google webmaster tools
google_verify: RWAhnQAwtW2Wc_v_kEhK_WFkNqcHJW47OzNxSGxz0A0

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: E1786FBC3A3BAFC5BF6F28B4E0654ADB

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: f0a868
  primary-rgb: "33, 150, 243"
  secondary: ffe8c2
  secondary-dark: 29455b
  section-tout: e4ffe1

# Build settings
markdown: kramdown
permalink: pretty
